### PR TITLE
Updated symfony/process constraint to allow 5.0

### PR DESCRIPTION
**Pull request by peterjaap**
Missed this one in my previous PR

### CODE REVIEW

**Comment by biggianteye** [comment]
How about including `symfony/event-dispatcher` as well?

**Comment by peterjaap** [comment]
@biggianteye good idea, done!

**Comment by peterjaap** [comment]
To make symfony/event-dispatcher work, I had to do some more fixes, which breaks BC with <5.0. So I removed those version numbers from composer.json now.

**Comment by Luc45** [comment]
Any plans to merge this?

**Comment by kezek** [comment]
Ho @peterjaap , any update on this ?

**Comment by peterjaap** [comment]
@kezek I'm not working with this lib anymore, feel free to contribute!

**Pull request closed without merging**
